### ISSUE TITLE
No check for GnuPG been installed

### ISSUE THREAD

**Issue by skvl** [skvl/git-privacy-manager#21]
GPM should test for GnuPG in `setup.py`.

```powershell
 gpm encrypt
Traceback (most recent call last):
  File "c:\users\skovalev\appdata\local\programs\python\python37\lib\site-packages\gnupg.py", line 842, in __init__
    p = self._open_subprocess(["--version"])
  File "c:\users\skovalev\appdata\local\programs\python\python37\lib\site-packages\gnupg.py", line 923, in _open_subprocess
    startupinfo=si)
  File "c:\users\skovalev\appdata\local\programs\python\python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\skovalev\appdata\local\programs\python\python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\skovalev\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\skovalev\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\skovalev\AppData\Local\Programs\Python\Python37\Scripts\gpm.exe\__main__.py", line 9, in <module>
  File "c:\users\skovalev\appdata\local\programs\python\python37\lib\site-packages\git_privacy_manager\command_line.py", line 4, in main
    git_privacy_manager.main()
  File "c:\users\skovalev\appdata\local\programs\python\python37\lib\site-packages\git_privacy_manager\gpm.py", line 142, in main
    gpg = gnupg.GPG()
  File "c:\users\skovalev\appdata\local\programs\python\python37\lib\site-packages\gnupg.py", line 846, in __init__
    raise OSError(msg)
OSError: Unable to run gpg (gpg) - it may not be available.
```

**Comment by skvl** [comment]
See [stackoverflow](https://stackoverflow.com/a/36902139):
-----
This solution is more transparent:

You will make a few additions to **setup.py** and there is no need to an extra file. 

Also you need to consider two different post-installations; one for development/editable mode and the other one for install mode.

Add these two classes that includes **your post-install** script to **setup.py**:

    from setuptools import setup
    from setuptools.command.develop import develop
    from setuptools.command.install import install
    
    
    class PostDevelopCommand(develop):
    	"""Post-installation for development mode."""
    	def run(self):
    		# PUT YOUR POST-INSTALL SCRIPT HERE or CALL A FUNCTION
    		develop.run(self)
    
    class PostInstallCommand(install):
    	"""Post-installation for installation mode."""
    	def run(self):
    		# PUT YOUR POST-INSTALL SCRIPT HERE or CALL A FUNCTION
    		install.run(self)
    
and insert `cmdclass` argument to `setup()` function in **setup.py**:

    setup(
        ...
    
    	cmdclass={
    		'develop': PostDevelopCommand,
    		'install': PostInstallCommand,
    	},
    
        ...
    )


You can even call shell commands during post-installation, like this:

    from setuptools import setup
    from setuptools.command.develop import develop
    from setuptools.command.install import install
    from subprocess import check_call
    

    class PostDevelopCommand(develop):
    	"""Post-installation for development mode."""
    	def run(self):
            check_call("apt-get install this-package".split())
    		develop.run(self)
    
    class PostInstallCommand(install):
    	"""Post-installation for installation mode."""
    	def run(self):
            check_call("apt-get install this-package".split())
    		install.run(self)
    
    
    setup(
    	...

*P.S. there is no any pre-install entry points available on setuptools. Read [this discussion](https://web.archive.org/web/20161202071142/https://bugs.python.org/setuptools/issue41) if you are wondering why there is none.*
